const DATABASENAME = "coachapp_db";
const DATABASEPASSWORD = "logicease123";
const DATABASEUSER = "root";
const DATABASEHOST = "localhost";
const DATABASETIMEZONE = "utc";
module.exports = {
    DATABASENAME: DATABASENAME,
    DATABASEPASSWORD: DATABASEPASSWORD,
    DATABASEUSER: DATABASEUSER,
    DATABASEHOST: DATABASEHOST,
    DATABASETIMEZONE: DATABASETIMEZONE
};